---

- name: Check current pip version
  ansible.builtin.shell: |
    set -o pipefail
    pip --version | sed "s/pip \(.*\) from .*/\1/"
  args:
    executable: /bin/bash
  changed_when: false
  register: pipv

- name: Debug | pip version
  ansible.builtin.debug:
    var: pipv.stdout

## does not seem to be handled well by ansible pip module
- name: Old pip
  when: pipv.stdout | int is version_compare('10.1', '<')
  block:

    - name: Upgrade pip to latest
      ansible.builtin.command:  # noqa no-changed-when
        cmd: pip install --upgrade pip
      when: ansible_facts['os_family'] != "Debian"

    - name: Upgrade setuptools to latest
      ansible.builtin.command:  # noqa no-changed-when
        cmd: pip install --upgrade setuptools
      when: ansible_facts['os_family'] != "Debian"
