---

## ubuntu xenial: 8.1, trusty: 1.5, centos7: 8.1
## trusty gets:
## https://github.com/Toblerity/Shapely/issues/305      ImportError: No module named packaging.version
## https://github.com/pypa/setuptools/issues/937
- name: check current pip version
  shell: |
    set -o pipefail
    pip --version | sed "s/pip \(.*\) from .*/\1/"
  args:
    executable: /bin/bash
  changed_when: false
  register: pipv

- debug: var=pipv.stdout

## does not seem to be handled well by ansible pip module
- block:

    - name: upgrade pip to latest
      command: pip install --upgrade pip
      when: ansible_os_family != "Debian"

    - name: upgrade setuptools to latest
      command: pip install --upgrade setuptools
      when: ansible_os_family != "Debian"

  when: pipv.stdout|int is version_compare( '10.1', '<')
