---
name: AnsibleCI

on:
  push:
  pull_request:
  schedule:  # run weekly, every monday 01:00
    - cron: '0 1 * * 1'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        # python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
        python-version: [3.8]
        molecule_distro:
          - 'centos:8'
          - 'centos:7'
          - 'ubuntu:20.04'
          - 'ubuntu:18.04'
    env:
      ANSIBLE_CALLBACK_WHITELIST: profile_tasks
      MOLECULE_NO_LOG: "false"

    steps:
      - uses: actions/checkout@v2
        with:
          path: juju4.zeek
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install molecule[docker] ansible-lint flake8 testinfra
      - name: run test
        run: |
          pwd
          find -ls
          cd $GITHUB_WORKSPACE/juju4.zeek && molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.molecule_distro }}
